config/routes.rb
Rails.application.routes.draw do
  get 'accounts' => 'accounts#index'
  resources :accounts do
    resources :deposits
    resources :withdrawals
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :deposits, dependent: :destroy
  has_many :withdrawals, dependent: :destroy

  def getBalance
    return getDeposits - getWithdrawals
  end

  def makeWithdrawal(withdrawal_params)
    self.withdrawals.create(withdrawal_params) unless getDeposits - getWithdrawals == 0
  end

  def makeDeposit(deposit_params)
    self.deposits.create(deposit_params)
  end

  private

  def getDeposits
    sum = 0
    self.deposits.each do |deposit|
      sum += deposit.amount
    end
    return sum
  end

  def getWithdrawals
    sum = 0
    self.withdrawals.each do |withdrawal|
      sum += withdrawal.amount
    end
    return sum
  end

end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
  belongs_to :account
end

app/models/withdrawal.rb
class Withdrawal < ActiveRecord::Base
  belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.create(account_params)
    redirect_to account_path(@account.id)
  end

  def show
    @account = Account.find(params[:id])
  end

  private
  def account_params
    params.require(:account).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController

  def new
    @account = Account.find(params[:account_id])
    @deposit = Deposit.new
  end

  def create
    @account = Account.find(params[:account_id])
    @account.makeDeposit(deposit_params)
    redirect_to account_path(@account.id)
  end

  private
  
  def deposit_params
    params.require(:deposit).permit(:amount)
  end
end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < ApplicationController

  def new
    @account = Account.find(params[:account_id])
    @withdrawal = Withdrawal.new
  end

  def create
    @account = Account.find(params[:account_id])
    @account.makeWithdrawal(withdrawal_params)
    redirect_to account_path(@account.id)
  end

  private

  def withdrawal_params
    params.require(:withdrawal).permit(:amount)
  end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/withdrawals_helper.rb
module WithdrawalsHelper
end

app/views/accounts/index.html.erb
<%= link_to "Open an account", new_account_path %>

app/views/accounts/new.html.erb
<%= form_for Account.new do |a| %>
  <%= a.label :name %>
  <%= a.text_field :name %>
  <%= a.submit %>
<% end %>

app/views/accounts/show.html.erb
Current Balance: <%= number_with_precision(@account.getBalance, precision: 2) %> </br>
<%= link_to "Make a deposit", new_account_deposit_path(@account.id) %>
<% if @account.getBalance > 0 %>
<%= link_to "Make a withdrawal", new_account_withdrawal_path(@account.id) %>
<% end %>

app/views/deposits/new.html.erb
<%= form_for [@account, @deposit] do |d| %>
  <%= d.label :amount %>
  <%= d.text_field :amount %>
  <%= d.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BankTechTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/withdrawals/new.html.erb
<%= form_for [@account, @withdrawal] do |d| %>
  <%= d.label :amount %>
  <%= d.text_field :amount %>
  <%= d.submit %>
<% end %>